chore: replace composer deps to begin refactor
dvsa/olcs-backend pull request #65
Opened 2024-02-12 16:07 UTC by fibble

## Description

WIP laminas-cli migration

Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

## Before submitting (or marking as "ready for review")

- [ ] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [ ] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2024-03-04 11:11 UTC, JoshuaLicense requested changes
Can we avoid using environment variables please? That doesn't look ideal.

Instead, I recommend we either use `$_SERVER['argv']` or `PHP_SAPI` ([docs](https://www.php.net/manual/en/function.php-sapi-name.php)) to determine what type of request it is _and/or_ pass a `--container` ([docs](https://docs.laminas.dev/laminas-cli/intro/#usage)) to the CLI command and overwrite the `Request` factory to return a CLI specific request object.

2024-03-04 11:11 UTC, JoshuaLicense commented on composer.json
Where are the `composer.lock` changes?

2024-03-04 12:08 UTC, fibble commented on composer.json
ah, ill update and push the lock!

2024-03-05 10:27 UTC, JoshuaLicense commented on composer.lock
Thanks for adding! Can we just update the dependencies that are required as part of this PR please.

`composer remove laminas/laminas-mvc-console` & `composer require laminas/laminas-cli` 🙏 

Also, during testing, we can point to the dev branch in `olcs-logging` - `composer require olcs/olcs-logging:dev-[branch]`

2024-03-07 11:28 UTC, JoshuaLicense reviewed
Looks good, will hold off approval until after testing though.

2024-03-18 14:34 UTC, merged